training:
  n_epochs: 100
  n_steps: 200000
  save_interval: 2
  sample_interval: 2
  validation_interval: 2
  accumulate_grad_batches: 4

testing:
  clip_denoised: False
  sample_num: 5

data:
  dataset_name: 'dataset_name'
  dataset_type: 'custom_aligned'
  dataset_config:
    dataset_path: 'dataset_path'
    image_size: 128
    channels: 3
    to_normal: True
    flip: True
  train:
    batch_size: 8
    shuffle: True
  val:
    batch_size: 8
    shuffle: True
  test:
    batch_size: 8
    # shuffle: False

model:
 
  VQGAN:
    params:
      in_channels: 3
      out_channels: 3
      down_block_types: 
        - DownEncoderBlock2D
 
      up_block_types: 
        - UpDecoderBlock2D
        - AttnUpDecoderBlock2D

      block_out_channels: [64, 64]
      layers_per_block: 2
      latent_channels: 3
      sample_size: 128

  BB:
    optimizer:
      weight_decay: 0.000
      optimizer: 'Adam'
      lr: 1.e-4
      beta1: 0.9

    lr_scheduler:
      factor: 0.5
      patience: 3000
      threshold: 0.0001
      cooldown: 3000
      min_lr: 5.e-7

    params:
      mt_type: 'linear' # options {'linear', 'sin'}
      objective: 'grad' # options {'grad', 'noise', 'ysubx'}
      loss_type: 'l1' # options {'l1', 'l2'}

      skip_sample: True
      sample_type: 'linear' # options {"linear", "sin"}
      sample_step: 200

      num_timesteps: 10 # timesteps
      eta: 1.0 # DDIM reverse process eta
      max_var: 1.0 # maximum variance

      UNetParams:
        sample_size: 128
        in_channels: 3
        out_channels: 3
        layers_per_block: 2
        block_out_channels : [128, 128, 256, 256, 512, 512]  # the number of output channels for each UNet block
        down_block_types:
            - DownBlock2D 
            - DownBlock2D
            - DownBlock2D
            - DownBlock2D
            - AttnDownBlock2D  
            - DownBlock2D
        
        up_block_types: 
            - UpBlock2D  
            - AttnUpBlock2D  
            - UpBlock2D
            - UpBlock2D
            - UpBlock2D
            - UpBlock2D
        